// @vitest-environment node
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {describe,it,expect,vi} from 'vitest';
import * as helpers from '../../supabase/functions/_shared/operational';
import * as help from '../../supabase/functions/_shared/assistant-help';
const UNIT='00000000-0000-0000-0000-000000000001';
function endpoint(options:{role?:boolean;appRole?:string;roleBusinessUnitId?:string|null;authenticated?:boolean;rateLimit?:boolean;reserveError?:string}={}){
 let handler!:(request:Request)=>Promise<Response>;
 const reads:{table:string;filters:Record<string,unknown>}[]=[];
 const rpc=vi.fn(async()=>({error:options.reserveError?{message:options.reserveError}:options.rateLimit?{message:'Limite de IA'}:null}));
 const textCompletion=vi.fn(async(..._args:unknown[])=>({text:JSON.stringify({action:'navigate',routeId:'stock',formId:null,fields:{},explanation:'Abra o Estoque.',missing:[]}),inputTokens:80,outputTokens:20}));
 const db={auth:{getUser:async()=>({data:{user:options.authenticated===false?null:{id:'staff'}},error:null})},rpc,from:(table:string)=>{
  const filters:Record<string,unknown>={};reads.push({table,filters});
 const result=()=>({data:table==='user_roles'?(options.role===false?[]:[{business_unit_id:options.roleBusinessUnitId===undefined?UNIT:options.roleBusinessUnitId,role:options.appRole??'admin'}]):table==='business_units'?{id:UNIT,name:'Confit'}:table==='ai_provider_credentials'?[{provider:'google',encrypted_key:'encrypted',iv:'iv'}]:[],error:null});
  const query={select:()=>query,eq:(key:string,value:unknown)=>{filters[key]=value;return query;},gte:()=>query,order:()=>query,limit:()=>query,maybeSingle:async()=>result(),update:()=>query,then:(resolve:(value:unknown)=>unknown,reject:(error:unknown)=>unknown)=>Promise.resolve(result()).then(resolve,reject)};return query;
 }};
 const source=readFileSync('supabase/functions/admin-assistant/index.ts','utf8').replace(/^import .*;\r?\n/gm,'');
 const code=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
 const ai={decryptAIKey:async()=>'secret',parseModelJson:(text:string)=>JSON.parse(text),providerJson:async()=>({models:[{name:'models/gemini-2.5-flash',supportedGenerationMethods:['generateContent']},{name:'models/image-model',supportedGenerationMethods:['generateContent']}] }),textCompletion};
 const params={...helpers,...help,...ai,createClient:()=>db,Deno:{env:{get:()=>''},serve:(fn:typeof handler)=>{handler=fn;}}};
 new Function(...Object.keys(params),code)(...Object.values(params));
 const body={action:'agent-plan',businessUnitId:UNIT,page:'/admin?sec=stock',model:'google/gemini-2.5-flash',prompt:'Consulte o Estoque',requestId:crypto.randomUUID()};
 return {reads,rpc,textCompletion,post:(overrides:Record<string,unknown>={},authorized=true)=>handler(new Request('https://test.co',{method:'POST',headers:authorized?{Authorization:'Bearer valid'}:{},body:JSON.stringify({...body,...overrides})}))};
}
describe('agent plan API authorization and scope',()=>{
 it('rejects anonymous requests and staff without access to the current route before credentials or provider access',async()=>{const anon=endpoint();expect((await anon.post({},false)).status).toBe(401);expect(anon.reads).toHaveLength(0);const staff=endpoint({appRole:'attendant'});expect((await staff.post()).status).toBe(403);expect(staff.reads.map(r=>r.table)).not.toContain('ai_provider_credentials');expect(staff.textCompletion).not.toHaveBeenCalled();});
 it('rejects another unit, arbitrary models, unknown routes and the removed conversation action',async()=>{const api=endpoint();expect((await api.post({businessUnitId:'00000000-0000-0000-0000-000000000002'})).status).toBe(403);expect((await api.post({model:'evil/provider'})).status).toBe(400);expect((await api.post({page:'/unknown'})).status).toBe(403);expect((await api.post({action:'chat'})).status).toBe(400);expect(api.textCompletion).not.toHaveBeenCalled();});
 it('plans a one-shot task without querying operational tables or exposing credentials',async()=>{const api=endpoint();const response=await api.post();expect(response.status).toBe(200);expect(await response.json()).toMatchObject({plan:{action:'navigate',routeId:'stock',explanation:'Abra o Estoque.'}});expect(api.textCompletion).toHaveBeenCalledOnce();const system=String(api.textCompletion.mock.calls[0][3]);expect(system).toContain('Rotas disponíveis para este papel');expect(system).not.toContain('encrypted');expect(system).not.toContain('secret');expect(api.reads.map(r=>r.table)).not.toContain('raw_materials');expect(api.reads.map(r=>r.table)).not.toContain('orders');expect(api.reads.map(r=>r.table)).not.toContain('menu_items');});
 it('does not invoke a paid completion after hitting the unit rate limit',async()=>{const api=endpoint({rateLimit:true});expect((await api.post()).status).toBe(429);expect(api.textCompletion).not.toHaveBeenCalled();});
 it('does not present the legacy unauthorized reservation as a generic quota error',async()=>{const api=endpoint({appRole:'attendant',reserveError:'Não autorizado'});const response=await api.post({page:'/atendimento'});expect(response.status).toBe(403);const data=await response.json();expect(data.error).toContain('habilitação da quota');expect(data.error).not.toContain('Limite de IA');expect(api.textCompletion).not.toHaveBeenCalled();});
 it('lists only verified models and returns no credentials',async()=>{const api=endpoint();const response=await api.post({action:'models'});const data=await response.json();expect(data.models).toEqual([{id:'google/gemini-2.5-flash',label:'Gemini 2.5 Flash',provider:'google'}]);expect(JSON.stringify(data)).not.toContain('secret');expect(JSON.stringify(data)).not.toContain('encrypted');expect(api.textCompletion).not.toHaveBeenCalled();});
 it('does not let an attendant use admin pages or receive an unauthorized target route',async()=>{const blocked=endpoint({appRole:'attendant'});expect((await blocked.post({action:'agent-plan',page:'/admin?sec=stock'})).status).toBe(403);expect(blocked.textCompletion).not.toHaveBeenCalled();const allowed=endpoint({appRole:'attendant'});allowed.textCompletion.mockResolvedValue({text:JSON.stringify({action:'navigate',routeId:'stock',formId:null,fields:{},explanation:'Dados do Estoque.',missing:[]}),inputTokens:1,outputTokens:1});const response=await allowed.post({action:'agent-plan',page:'/atendimento',prompt:'Abra o estoque'});expect(response.status).toBe(200);expect((await response.json()).plan).toMatchObject({action:'clarify',routeId:'service',explanation:'Esse módulo não está liberado para o seu perfil. Posso orientar a partir da página atual.'});});
 it('does not wildcard a null-scoped non-admin role and accepts a global admin',async()=>{const legacy=endpoint({appRole:'attendant',roleBusinessUnitId:null});expect((await legacy.post({page:'/atendimento'})).status).toBe(403);const globalAdmin=endpoint({appRole:'admin',roleBusinessUnitId:null});expect((await globalAdmin.post({page:'/admin?sec=stock'})).status).toBe(200);});
 it('uses a neutral explanation when an authorized task omits explanation',async()=>{const api=endpoint();api.textCompletion.mockResolvedValue({text:JSON.stringify({action:'explain',routeId:'stock',formId:null,fields:{},missing:[]}),inputTokens:1,outputTokens:1});const response=await api.post();expect(response.status).toBe(200);expect((await response.json()).plan.explanation).toBe('Posso orientar a partir deste módulo.');});
 it('reports task JSON failures without document or file guidance',async()=>{const api=endpoint();api.textCompletion.mockResolvedValue({text:'not json',inputTokens:1,outputTokens:1});const response=await api.post();expect(response.status).toBe(503);const data=await response.json();expect(data.error).toContain('Reformule a solicitação');expect(data.error).not.toContain('arquivo');});
 it('accepts only the guided menu draft and rejects write actions from the model',async()=>{const supported=endpoint();supported.textCompletion.mockResolvedValue({text:JSON.stringify({action:'draft',routeId:'menu',formId:'menu-guided',fields:{name:'Burger da Casa',price:'42,90',unknown:'não aceitar'},explanation:'Rascunho local',missing:[]}),inputTokens:1,outputTokens:1});const proposal=await supported.post({page:'/admin?sec=menu'});expect(proposal.status).toBe(200);expect((await proposal.json()).plan.fields).toEqual({name:'Burger da Casa',price:'42,90'});const unsupported=endpoint();unsupported.textCompletion.mockResolvedValue({text:JSON.stringify({action:'draft',routeId:'stock',formId:'stock-purchase',fields:{price:'100'},explanation:'Rascunho',missing:[]}),inputTokens:1,outputTokens:1});expect((await unsupported.post({prompt:'Registre compra'})).status).toBe(503);const forbidden=endpoint();forbidden.textCompletion.mockResolvedValue({text:JSON.stringify({action:'save',routeId:'menu',formId:null,fields:{},explanation:'Salvei',missing:[]}),inputTokens:1,outputTokens:1});expect((await forbidden.post({prompt:'Salve produto'})).status).toBe(503);});
});
