import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {MemoryRouter,Routes,Route,useLocation} from 'react-router-dom';
import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import AdminAssistant from '@/components/AdminAssistant';
import {AGENT_PAGES,TUTORIALS,findAgentPage} from '../../supabase/functions/_shared/assistant-help';
const mocks=vi.hoisted(()=>({roles:['admin'],unit:'u1',invoke:vi.fn()}));
vi.mock('@/hooks/useAuth',()=>({useAuth:()=>({user:{id:'staff'}})}));
vi.mock('@/hooks/useUnitRoles',()=>({useUnitRoles:()=>({roles:mocks.roles,loading:false})}));
vi.mock('@/hooks/useCurrentBusinessUnit',()=>({useCurrentBusinessUnit:()=>({businessUnitId:mocks.unit,units:[{id:'u1',name:'Confit'},{id:'u2',name:'Outra'}],loading:false})}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{functions:{invoke:mocks.invoke}}}));
function Page(){const location=useLocation();return <p data-testid="page">{location.pathname+location.search}</p>;}
function App({path='/admin?sec=stock'}:{path?:string}){return <MemoryRouter initialEntries={[path]}><Routes><Route path="*" element={<Page/>}/></Routes><AdminAssistant/></MemoryRouter>;}
const menuPlan={action:'draft',routeId:'menu',formId:'menu-guided',fields:{name:'Burger da Casa',category:'hamburgueres',price:'42,90'},explanation:'Preparei um rascunho local com os dados informados.',missing:['Ingredientes e quantidades'],};
beforeEach(()=>{mocks.roles=['admin'];mocks.unit='u1';mocks.invoke.mockReset();mocks.invoke.mockImplementation(async(_name,{body})=>body.action==='models'?{data:{models:[{id:'google/gemini-2.5-flash',label:'Gemini',provider:'google'}],warnings:[]},error:null}:{data:{plan:{action:'navigate',routeId:'stock',formId:null,fields:{},explanation:'Vou abrir o Estoque para explicar o registro de compra.',missing:[]}},error:null});Element.prototype.scrollIntoView=vi.fn();});
afterEach(cleanup);
describe('agente PØP9',()=>{
 it('oferece ao menos uma instrução para cada rota operável',()=>{const missing=AGENT_PAGES.filter(page=>!TUTORIALS.some(tutorial=>findAgentPage(tutorial.page)?.id===page.id));expect(missing.map(page=>page.id)).toEqual([]);});
 it('respeita o papel e não aparece em rotas públicas ou fora do catálogo',()=>{mocks.roles=['attendant'];const view=render(<App/>);expect(screen.queryByRole('button',{name:'Abrir agente PØP9'})).not.toBeInTheDocument();view.unmount();render(<App path="/atendimento"/>);expect(screen.getByRole('button',{name:'Abrir agente PØP9'})).toBeInTheDocument();cleanup();render(<App path="/pedir/u1"/>);expect(screen.queryByRole('button',{name:'Abrir agente PØP9'})).not.toBeInTheDocument();expect(mocks.invoke).not.toHaveBeenCalled();});
 it('fornece instruções locais e só navega para módulos autorizados',async()=>{render(<App path="/caixa"/>);fireEvent.click(screen.getByRole('button',{name:'Abrir agente PØP9'}));fireEvent.click(screen.getByRole('tab',{name:'Instruções'}));expect(screen.getByText('Passo 1 de 5')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Próximo passo'}));expect(screen.getByText('Passo 2 de 5')).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Escolher instrução'),{target:{value:'cashier'}});expect(screen.getByText('Passo 1 de 5')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Abrir área'}));expect(screen.getByTestId('page')).toHaveTextContent('/caixa');await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());});
 it('envia uma tarefa sem histórico e abre automaticamente apenas a rota autorizada',async()=>{render(<App path="/admin?sec=menu"/>);fireEvent.click(screen.getByRole('button',{name:'Abrir agente PØP9'}));await waitFor(()=>expect(screen.getByLabelText('Modelo do agente')).toHaveValue('google/gemini-2.5-flash'));fireEvent.change(screen.getByLabelText('Descreva a tarefa'),{target:{value:'Abra Estoque e explique como lançar uma compra'}});fireEvent.click(screen.getByRole('button',{name:'Analisar tarefa'}));await waitFor(()=>expect(screen.getByTestId('page')).toHaveTextContent('/admin?sec=stock'));const args=mocks.invoke.mock.calls.find(([,opts])=>opts.body.action==='agent-plan')[1].body;expect(args.businessUnitId).toBe('u1');expect(args.page).toBe('/admin?sec=menu');expect(args.prompt).toContain('lançar uma compra');expect(args.requestId).toMatch(/^[a-f0-9-]{36}$/);expect(screen.queryByRole('tab',{name:'Conversa'})).not.toBeInTheDocument();await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());});
 it('mostra e aplica somente campos allowlisted ao rascunho local, sem persistir',async()=>{mocks.invoke.mockImplementation(async(_name,{body})=>body.action==='models'?{data:{models:[{id:'google/gemini-2.5-flash',label:'Gemini',provider:'google'}],warnings:[]}}:{data:{plan:menuPlan}});render(<App path="/admin?sec=menu"/>);fireEvent.click(screen.getByRole('button',{name:'Abrir agente PØP9'}));await waitFor(()=>expect(screen.getByLabelText('Modelo do agente')).toHaveValue('google/gemini-2.5-flash'));fireEvent.change(screen.getByLabelText('Descreva a tarefa'),{target:{value:'Monte um burger chamado Burger da Casa por 42,90'}});fireEvent.click(screen.getByRole('button',{name:'Analisar tarefa'}));await waitFor(()=>expect(screen.getByText('Preparei um rascunho local com os dados informados.')).toBeInTheDocument());expect(screen.getByText('Rascunho local · não salvo')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Aplicar ao rascunho local'}));expect(screen.getByRole('tab',{name:'Rascunho de cardápio'})).toHaveAttribute('aria-selected','true');expect(screen.getByLabelText('Nome do produto')).toHaveValue('Burger da Casa');expect(mocks.invoke.mock.calls.every(([,opts])=>!['save','apply','submit'].includes(opts.body.action))).toBe(true);});
 it('descarta o rascunho da unidade anterior antes de exibir o painel na nova unidade',async()=>{mocks.invoke.mockImplementation(async(_name,{body})=>body.action==='models'?{data:{models:[{id:'google/gemini-2.5-flash',label:'Gemini',provider:'google'}],warnings:[]}}:{data:{plan:menuPlan}});const view=render(<App path="/admin?sec=menu"/>);fireEvent.click(screen.getByRole('button',{name:'Abrir agente PØP9'}));await waitFor(()=>expect(screen.getByLabelText('Modelo do agente')).toHaveValue('google/gemini-2.5-flash'));fireEvent.change(screen.getByLabelText('Descreva a tarefa'),{target:{value:'Monte Burger da Casa'}});fireEvent.click(screen.getByRole('button',{name:'Analisar tarefa'}));await waitFor(()=>expect(screen.getByText('Preparei um rascunho local com os dados informados.')).toBeInTheDocument());fireEvent.click(screen.getByRole('button',{name:'Aplicar ao rascunho local'}));expect(screen.getByLabelText('Nome do produto')).toHaveValue('Burger da Casa');mocks.unit='u2';view.rerender(<App path="/admin?sec=menu"/>);fireEvent.click(screen.getByRole('button',{name:'Abrir agente PØP9'}));fireEvent.click(screen.getByRole('tab',{name:'Rascunho de cardápio'}));expect(screen.getByLabelText('Nome do produto')).toHaveValue('');});
 it('descarta proposta em andamento e rascunho quando a unidade muda',async()=>{let finish:(value:unknown)=>void=()=>{};mocks.invoke.mockImplementation(async(_name,{body})=>body.action==='models'?{data:{models:[{id:'google/gemini-2.5-flash',label:'Gemini',provider:'google'}],warnings:[]}}:new Promise(resolve=>{finish=resolve;}));const view=render(<App path="/admin?sec=stock"/>);fireEvent.click(screen.getByRole('button',{name:'Abrir agente PØP9'}));await waitFor(()=>expect(screen.getByLabelText('Modelo do agente')).toHaveValue('google/gemini-2.5-flash'));fireEvent.change(screen.getByLabelText('Descreva a tarefa'),{target:{value:'Veja o estoque da Confit'}});fireEvent.click(screen.getByRole('button',{name:'Analisar tarefa'}));mocks.unit='u2';view.rerender(<App path="/admin?sec=stock"/>);finish({data:{plan:{action:'explain',routeId:'stock',formId:null,fields:{},explanation:'Dados da Confit',missing:[]}}});fireEvent.click(screen.getByRole('button',{name:'Abrir agente PØP9'}));await waitFor(()=>expect(screen.getByLabelText('Modelo do agente')).toHaveValue('google/gemini-2.5-flash'));expect(screen.queryByText('Dados da Confit')).not.toBeInTheDocument();expect(screen.queryByText('Veja o estoque da Confit')).not.toBeInTheDocument();expect(screen.getByText('Outra · Administrador · Estoque')).toBeInTheDocument();});
});
