import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {MemoryRouter,Routes,Route,useLocation} from 'react-router-dom';
import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import AdminAssistant from '@/components/AdminAssistant';
const mocks=vi.hoisted(()=>({roles:['admin'],unit:'u1',invoke:vi.fn()}));
vi.mock('@/hooks/useAuth',()=>({useAuth:()=>({user:{id:'admin'}})}));
vi.mock('@/hooks/useUnitRoles',()=>({useUnitRoles:()=>({roles:mocks.roles,loading:false})}));
vi.mock('@/hooks/useCurrentBusinessUnit',()=>({useCurrentBusinessUnit:()=>({businessUnitId:mocks.unit,units:[{id:'u1',name:'Confit'},{id:'u2',name:'Outra'}]})}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{functions:{invoke:mocks.invoke}}}));
function Page(){const location=useLocation();return <p data-testid="page">{location.pathname+location.search}</p>;}
function App({path='/admin?sec=stock'}:{path?:string}){return <MemoryRouter initialEntries={[path]}><Routes><Route path="*" element={<Page/>}/></Routes><AdminAssistant/></MemoryRouter>;}
beforeEach(()=>{mocks.roles=['admin'];mocks.unit='u1';mocks.invoke.mockReset();mocks.invoke.mockResolvedValue({data:{models:[]},error:null});Element.prototype.scrollIntoView=vi.fn();});
afterEach(cleanup);
describe('administrator assistant',()=>{
 it('hides the assistant from attendants and public customer routes',()=>{mocks.roles=['attendant'];const view=render(<App/>);expect(screen.queryByRole('button',{name:'Abrir assistente de IA e tutoriais'})).not.toBeInTheDocument();mocks.roles=['admin'];view.unmount();render(<App path="/pedir/u1"/>);expect(screen.queryByRole('button',{name:'Abrir assistente de IA e tutoriais'})).not.toBeInTheDocument();expect(mocks.invoke).not.toHaveBeenCalled();});
 it('offers local step-by-step tutorials without an AI credential and opens the correct area',async()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:'Abrir assistente de IA e tutoriais'}));fireEvent.click(screen.getByRole('tab',{name:'Tutoriais'}));expect(screen.getByText('Passo 1 de 5')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Próximo passo'}));expect(screen.getByText('Passo 2 de 5')).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Escolher tutorial'),{target:{value:'cashier'}});expect(screen.getByText('Passo 1 de 5')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Abrir área'}));expect(screen.getByTestId('page')).toHaveTextContent('/caixa');await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());});
 it('sends the chosen unit, page and read context and displays a provider failure without claiming completion',async()=>{mocks.invoke.mockImplementation(async(_name,{body})=>body.action==='models'?{data:{models:[{id:'google/gemini-2.5-flash',label:'Gemini',provider:'google'}]}}:{error:{context:{json:async()=>({error:'Limite do provedor atingido'})}}});render(<App/>);fireEvent.click(screen.getByRole('button',{name:'Abrir assistente de IA e tutoriais'}));await waitFor(()=>expect(screen.getByLabelText('Modelo de conversa')).toHaveValue('google/gemini-2.5-flash'));fireEvent.change(screen.getByLabelText('Dados para consultar'),{target:{value:'stock'}});fireEvent.change(screen.getByLabelText('Mensagem para o assistente'),{target:{value:'Quais insumos estão abaixo do mínimo?'}});fireEvent.click(screen.getByRole('button',{name:'Enviar mensagem'}));await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('Limite do provedor atingido'));const args=mocks.invoke.mock.calls.find(([,opts])=>opts.body.action==='chat')[1].body;expect(args.businessUnitId).toBe('u1');expect(args.context).toBe('stock');expect(args.page).toBe('/admin?sec=stock');expect(args.requestId).toMatch(/^[a-f0-9-]{36}$/);expect(screen.getByLabelText('Mensagem para o assistente')).toHaveValue('Quais insumos estão abaixo do mínimo?');});
 it('discards an in-flight answer and previous history when the unit changes',async()=>{let finish:(value:unknown)=>void=()=>{};mocks.invoke.mockImplementation(async(_name,{body})=>body.action==='models'?{data:{models:[{id:'google/gemini-2.5-flash',label:'Gemini',provider:'google'}]}}:new Promise(resolve=>{finish=resolve;}));const view=render(<App/>);fireEvent.click(screen.getByRole('button',{name:'Abrir assistente de IA e tutoriais'}));await waitFor(()=>expect(screen.getByLabelText('Modelo de conversa')).toHaveValue('google/gemini-2.5-flash'));fireEvent.change(screen.getByLabelText('Mensagem para o assistente'),{target:{value:'Estoque da Confit'}});fireEvent.click(screen.getByRole('button',{name:'Enviar mensagem'}));mocks.unit='u2';view.rerender(<App/>);finish({data:{reply:'Dados da Confit'}});fireEvent.click(screen.getByRole('button',{name:'Abrir assistente de IA e tutoriais'}));await waitFor(()=>expect(screen.getByLabelText('Modelo de conversa')).toHaveValue('google/gemini-2.5-flash'));expect(screen.queryByText('Dados da Confit')).not.toBeInTheDocument();expect(screen.queryByText('Estoque da Confit')).not.toBeInTheDocument();expect(screen.getByText('Outra · Administrador')).toBeInTheDocument();});
});
