// @vitest-environment node
import {describe,it,expect} from "vitest";
import {hmac,equal,publicOrigin,incomingMessages,botDestination} from "../../supabase/functions/_shared/operational";
import {crmReport} from "@/utils/crm";
import {orderLink,whatsappLink} from "@/utils/operationalLinks";
describe("operational links and Meta payloads",()=>{
  it("signs exact bytes and rejects nonpublic endpoints",async()=>{expect(await hmac("secret","payload")).toHaveLength(64);expect(equal(await hmac("secret","payload"),await hmac("secret","changed"))).toBe(false);expect(publicOrigin("https://loja.com")).toBe("https://loja.com");for(const value of ["http://loja.com","https://127.0.0.1","https://localhost","https://admin:pass@loja.com","https://loja.com/caminho"]){expect(()=>publicOrigin(value)).toThrow();}expect(botDestination("https://bot.com/webhook")).toBe("https://bot.com/webhook");});
  it("ignores status receipts and keeps each message bound to its Meta number",()=>{const messages=incomingMessages({object:"whatsapp_business_account",entry:[{changes:[{value:{metadata:{phone_number_id:"number"},contacts:[{wa_id:"5511999999999",profile:{name:"João"}}],messages:[{id:"wamid.a",from:"5511999999999",type:"text",text:{body:"PEDIR"}}]}}]}]});expect(messages).toEqual([{id:"wamid.a",phone:"5511999999999",name:"João",text:"PEDIR",type:"text",phoneId:"number"}]);expect(incomingMessages({object:"whatsapp_business_account",entry:[{changes:[{value:{statuses:[{id:"a"}]}}]}]})).toEqual([]);});
  it("generates shareable links without customer identifiers",()=>{expect(orderLink("https://loja.com","unit")).toBe("https://loja.com/pedir/unit?origem=whatsapp");expect(orderLink("javascript:alert(1)","unit")).toBe("");expect(whatsappLink("+55 (11) 99999-9999")).toBe("https://wa.me/5511999999999?text=PEDIR");});
  it("joins WhatsApp and visits by Brazilian phone without inflating visit counts",()=>{const report=crmReport([{id:"visit",customer_id:"id",name:"João",phone:"11999999999",email:null,added_at:"2026-10-01"}],[{id:"order",client_id:"visit",placed_at:"2026-10-01",total:50,status:"delivered"}],[{id:"contact",phone:"5511999999999",name:"João",email:null,bairro:"Centro",preferences:"Burger",profile_consent_at:"2026-10-02",marketing_consent_at:null,opted_out_at:null,message_count:4,first_seen_at:"2026-10-02",last_seen_at:"2026-10-03"}]);expect(report).toHaveLength(1);expect(report[0].visits.size).toBe(1);expect(report[0].messages).toBe(4);expect(report[0].total).toBe(50);expect(report[0].marketingConsent).toBe(false);});
});
