export type CrmVisit={id:string;customer_id:string|null;name:string;phone:string|null;email:string|null;added_at:string};
export type CrmOrder={id:string;client_id:string|null;placed_at:string;total:number|null;status:string};
export type WhatsAppContact={id:string;phone:string;name:string;email:string|null;bairro:string|null;preferences:string|null;profile_consent_at:string|null;marketing_consent_at:string|null;opted_out_at:string|null;message_count:number;first_seen_at:string;last_seen_at:string};
export type CrmCustomer={key:string;name:string;phone:string|null;email:string|null;bairro:string|null;preferences:string|null;visits:Set<string>;orders:number;total:number;last:string;first:string;messages:number;whatsapp:boolean;marketingConsent:boolean};
export function normalizeCrmPhone(phone:string|null){const digits=(phone ?? "").replace(/\D/g,"");return digits.length===10 || digits.length===11 ? `55${digits}` : digits;}
export function crmReport(visits:CrmVisit[],orders:CrmOrder[],contacts:WhatsAppContact[],cutoff=0){
  const grouped=new Map<string,CrmCustomer>();const visitKeys=new Map<string,string>();
  const empty=(key:string,name:string,phone:string|null,email:string|null,first:string,last:string):CrmCustomer=>({key,name,phone,email,bairro:null,preferences:null,visits:new Set(),orders:0,total:0,last,first,messages:0,whatsapp:false,marketingConsent:false});
  for(const visit of visits){const phone=normalizeCrmPhone(visit.phone);const key=phone.length>=10 ? `phone:${phone}` : visit.customer_id ? `id:${visit.customer_id}` : `visit:${visit.id}`;visitKeys.set(visit.id,key);if(!grouped.has(key))grouped.set(key,empty(key,visit.name,visit.phone,visit.email,visit.added_at,visit.added_at));const row=grouped.get(key)!;row.visits.add(visit.id);if(visit.added_at>row.last){row.last=visit.added_at;row.name=visit.name;}if(visit.added_at<row.first)row.first=visit.added_at;}
  for(const contact of contacts){const key=`phone:${normalizeCrmPhone(contact.phone)}`;if(!grouped.has(key))grouped.set(key,empty(key,contact.name,contact.phone,contact.email,contact.first_seen_at,contact.last_seen_at));const row=grouped.get(key)!;row.whatsapp=true;row.messages=contact.message_count;row.marketingConsent=Boolean(contact.marketing_consent_at) && !contact.opted_out_at;row.bairro=contact.bairro;row.preferences=contact.preferences;if(contact.last_seen_at>=row.last){row.name=contact.name;row.email=contact.email ?? row.email;row.last=contact.last_seen_at;}if(contact.first_seen_at<row.first)row.first=contact.first_seen_at;}
  for(const order of orders){const key=order.client_id ? visitKeys.get(order.client_id) : undefined;const row=key ? grouped.get(key) : null;if(!row || order.status==="cancelled" || new Date(order.placed_at).getTime()<cutoff)continue;row.orders++;row.total+=Number(order.total ?? 0);}
  return [...grouped.values()].filter(row=>!cutoff || new Date(row.last).getTime()>=cutoff || row.orders>0).sort((a,b)=>b.total-a.total);
}
