// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const hasValidUrl = typeof SUPABASE_URL === 'string' && SUPABASE_URL.length > 0;
const hasValidKey = typeof SUPABASE_PUBLISHABLE_KEY === 'string' && SUPABASE_PUBLISHABLE_KEY.length > 0;

if (!hasValidUrl || !hasValidKey) {
  const msg = '[Supabase] Faltam variáveis de ambiente: VITE_SUPABASE_URL e/ou VITE_SUPABASE_PUBLISHABLE_KEY. Crie um arquivo .env com essas chaves.';
  if (import.meta.env.DEV) {
    console.warn(msg);
  } else {
    console.error(msg);
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  hasValidUrl ? SUPABASE_URL : '',
  hasValidKey ? SUPABASE_PUBLISHABLE_KEY : '',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);